name: Documentation Version Release
on:
  push:
    tags:        
      - '*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of documentation to generate and release, x.y.z'     
        required: true
jobs:
  docs-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Set Version ➕
        run: |
          if [ -z ${{ github.event.inputs.version }} ]; then echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV; else echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV; fi
      - name: Release 🌱
        run: |
          cd docs/source && pip install -r requirements.txt
          cd ../
          ./bin/build_docs.sh $RELEASE_VERSION
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          keep_files: true
          enable_jekyll: true
          exclude_assets: '.github,docs/_data/versions.yaml'
      
