name: Github Pages Update
on:
  push:
    paths:
    - "docs/**"
    branches: [main]
jobs:
  deploy-docs:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          keep_files: true
          enable_jekyll: true
          exclude_assets: '.github,docs/_data/versions.yaml'